version: '3.8'

name: '${APP_NAME}'

services:
  db:
    image: postgres:15.4-bullseye
    env_file: ./.env
    ports: ['5432:5432']
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgresql-dyplom-data:/var/lib/postgresql/data:rw

volumes:
  postgresql-dyplom-data:
